name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install modules
        run: yarn
      - name: Run unit tests
        run: yarn test:unit
      - name: Run integration tests [basic]
        run: yarn test:integration:basic
      - name: Run integration tests [internal-writes]
        run: yarn test:integration:internal-writes
      - name: Run integration tests [wasm]
        run: yarn test:integration:wasm
      - name: Run regression tests
        run: yarn test:regression

